### ISSUE TITLE
Add Portuguese Translations

### ISSUE THREAD

**Issue by aimproxy** [manexim/home#19]
Hi, I'm a native Portuguese, I saw your app donsen't have Portuguese translations, can I add this by making a PR?

**Comment by meisenzahl** [comment]
It would be really great if you could contribute Portuguese translations. Yes you can add them by making a PR. Please branch from `develop`.  I have already added the required files there.

**Comment by aimproxy** [comment]
Ok, this weekend I will start translating into Portuguese! You can  assignee this to me!

**Comment by meisenzahl** [comment]
Thanks in advance for the translation!

**Comment by aimproxy** [comment]
Pull request successfully merged and closed  #21
