### ISSUE TITLE
Could it be possible to add this?

### ISSUE THREAD

**Issue by Hedronmx** [manexim/home#8]
There´s this software
https://github.com/AlbertMN/AssistantComputerControl
 It is checking constantly for a file being written, when done so, it executes an action like shutting down or volumen up.

Not sure if this is out of scope but it would be nice to have.

**Comment by meisenzahl** [comment]
Which functionality do you want exactly?

If I understand it correctly, you can send commands to [AlbertMN/AssistantComputerControl](https://github.com/AlbertMN/AssistantComputerControl) via digital assistants using voice commands. It uses IFTT and Dropbox.

See [AlbertMN/AssistantComputerControl](https://github.com/AlbertMN/AssistantComputerControl) README:
_Note: [IFTTT](https://ifttt.com/) and a [Dropbox](https://www.dropbox.com/) account is required for the default setup. Dropbox will need to be running at all times for ACC to work_

I would like to avoid being dependent on cloud services. In addition, Home is supposed to be a control center for local smart home gadgets. [AlbertMN/AssistantComputerControl](https://github.com/AlbertMN/AssistantComputerControl), on the other hand, should control your computer.

A daemon would probably be better suited for a Linux distribution than a graphical application. For example, have you seen TRIGGERcmd yet?

[TRIGGERcmd: Remotely run commands on your computers.](https://www.triggercmd.com/)
[Voice control Linux using Alexa or Google Assistant. - FreeYourDesktop](https://www.freeyourdesktop.com/2019/02/voice-control-linux-using-alexa-or-google-assistant/)

**Comment by meisenzahl** [comment]
Closed because it doesn't seem to be relevant to the project.
