### ISSUE TITLE
Set custom icons for bulbs

### ISSUE THREAD

**Issue by danirabbit** [manexim/home#9]
It would be great to be able to select icons for the bulb for faster recognition.

For example, here's the selection of icons that HomeKit offers:

![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.activejr.com%2Fwp-content%2Fuploads%2F2018%2F05%2FHow-to-change-HomeKit-ioncs.jpg&f=1)

**Comment by meisenzahl** [comment]
On `develop` you can now click on the icon on the overview page of a device and select your own icon. The available icons can be found at https://github.com/manexim/home/tree/develop/data/icons/symbolic. You can select icons starting with `com.github.manexim.home.icon.`. The icons are only symbolic. The selection of the icons is saved in the configuration and automatically loaded at the next start.
